2-sample T-tests allow you to compare the averages between two groups.

1. How big is the difference between these two groups
(and how much uncertainty accompanies this estimate?)

2. Do we have evidence whether the difference differs from zero?


<!--chapter:end:Chapter_7_2_sample_T_Tests_1.Rmd-->

This website does not consider non-parametric tests to compare measures of central tendency (e.g., median value or average value) between groups for two reasons.  First, non-parametric tests involve (often unappreciated) assumptions that hinder analyses.  For example, researchers often use a Mann-Whitney U test to analyse data that fail to meet the assumptions of a t-test; here, researchers aim to evaluate evidence that the median values differ between the groups. 

This approach can be problematic, however, because Mann-Whitney U tests provide evidence for whether two distributions differ in general (i.e., including shape), not for whether median values differ between two distributions, specifically.  Therefore, if two distributions being compared differ in shape, then a small p-value might arise from a Mann-Whitney U test (at least in part) due to shape differences, and not due differences in median values. 

In other words, in order to use a Mann-Whitney U test to evaluate evidence for different median values between groups, the researcher must be confident that the two distributions have similar shapes.  Such unappreciated assumptions make non-parametric tests less desirable.  Second, non-parametric methods cannot provide meaningful estimates of effect size with appropriate uncertainty. 

As analyses of effect size offer more insight than those that focus on p-values (see Chapter 8: Abandon statistical significance, non-parametric tests have less to offer than alternative methods, such as computational approaches (randomization / permutation tests, bootstrapping).

<!--chapter:end:Chapter_7_introduction_Note.Rmd-->

**This chapter explores how to compare the average of a group to something else for simple experimental designs.** 

For instance, one of the most common questions that researchers ask is, “Do we have evidence that the average value of a trait in one group differs from the average for anther group?”. `U+1F34E`

Alternatively, a researcher might wish to test whether the mean value of a group differs from a specified value (e.g., Does the mean temperature of a group of subjects in a cold room differ from 37 degrees Celsius?).  This chapter explores t-tests as a way to answer these questions.

Note that the videos in this chapter discuss results of t-tests in terms of statistical significance (we will update these videos, in this respect).  In this light, we particularly draw your attention to the Practice Problems and Answers for this chapter because these materials demonstrate a more modern interpretation of t-tests by focusing on effect size. 

The Practice Problems and Answers also follow the advice in the next Chapter, by abandoning the concept of statistical significance, and show how to test assumptions.

<!--chapter:end:Chapter_7_introduction.Rmd-->

## test header

this is a sentence written in **bold** and in _italics_

I also am including some code:

````
variable <- 2+3
````

Now I am referring to the `variable` as in-line code

Next I want to include some math:

$$variable = 2+3$$

and now some text below it as well.


<!--chapter:end:R_markdown_test_wo_header.Rmd-->

